Add support for more file types for SVF analysis
* Analyzer now supports Executables, Static and Shared C libraries
* Build the packages only one time

diff --git a/svf/scripts/analyzer_svf b/svf/scripts/analyzer_svf
--- a/svf/scripts/analyzer_svf
+++ b/svf/scripts/analyzer_svf
@@ -5,73 +5,119 @@ VERSION_T="$(cat $1 | grep 'Version: ' | cut -d ':' -f2)"
 NAME="$(echo -e "${NAME_T}" | tr -d '[:space:]')"
 VERSION="$(echo -e "${VERSION_T}" | tr -d '[:space:]')"
 PKG="$NAME-$VERSION"
-CALLGRAPH="$PKG.txt"
 ERROR="$PKG.err"
-
 cd $2
-make clean
-# Setup SVF
-echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main" >> \
-    /etc/apt/sources.list
-echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main" >> \
-    /etc/apt/sources.list
-wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
-apt -yqq update && apt -yqq upgrade
-apt install -yqq llvm-7 clang-7
-ln -s /usr/bin/clang-7 /usr/bin/clang
-ln -s /usr/bin/llvm-link-7 /usr/bin/llvm-link
-export LLVM_SRC=/usr/local/installations/llvm-7.0.0.src
-export LLVM_OBJ=/usr/lib/llvm-7/build
-export LLVM_DIR=/usr/lib/llvm-7/build
-export SVF_HOME=/usr/local/installations/SVF/
-export PATH=$SVF_HOME/Release-build/bin:$PATH
-export LLVM_COMPILER=clang
-# replace '=' and ':=' with '?=' in rules Makefile
-sed -i -E "s/CC [:]?=/CC ?=/g" debian/rules
-sed -i -E "s/CC[:]?=/CC?=/g" debian/rules
-# find -maxdepth 1 -type f -executable -exec sh -c "file -i '{}' | grep -q 'x-executable; charset=binary'" \; -print
-# run SVF on package
-CC=/usr/local/bin/wllvm dpkg-buildpackage 2>error
-# sed to chang CC := or = with ?=
-STATUS=$?
-BINARIES=$(find -maxdepth 1 -type f -executable -exec sh -c \
-    "file -i '{}' | grep -q 'charset=binary'" \; -print)
-# Check if there are binaries
-if [ -z "$BINARIES" ] && [ $STATUS == 0 ]; then
-    echo "$PKG: no binary files found" >> /callgraphs/report && \
-    exit 0
-elif [[ -f "error" ]] && [ $STATUS != 0 ]; then
-    echo "$PKG: compilation failure" >> /callgraphs/report && \
-        mv error /callgraphs/$ERROR && \
-        exit 0
-fi
-for i in $BINARIES; do
-    i=${i#./}
-    # extract LLVM bitcode
-    extract-bc $i 2> error
-    STATUS=$?
-    # Check if there are .bc files
-    count=`ls -1 *.bc 2>/dev/null | wc -l`
-    if [ $count == 0 ] && [ $STATUS == 0 ]; then
-        echo "$PKG: $i no .bc files produced" >> /callgraphs/report && \
-            if [[ -f "error" ]]; then
-                mv error /callgraphs/$PKG.$i.ext.err
-            fi
-    elif [[ -f "error" ]] && [ $STATUS != 0 ] ; then
-        echo "$PKG: $i extract-bc failed" >> /callgraphs/report && \
-            mv error /callgraphs/$PKG.$i.ext.err
-    fi
-    # Run SVF analysis
-    for j in *.bc; do
-        wpa -fspta -dump-callgraph $j 2> error
-        if [[ -f "callgraph_final.dot" ]]; then
-            echo "$PKG: $i done" >> /callgraphs/report && \
-                mv callgraph_final.dot /callgraphs/$PKG.$i.dot && \
-                rm -f callgraph_initial.dot j
-        elif [[ -f "error" ]] && [ $STATUS != 0 ]; then
-            echo "$PKG: $i SVF failed" >> /callgraphs/report &&
-                mv error /callgraphs/$PKG.$i.svf.err
-        fi
-        rm -f *.bc
+HOME_DIR=$(pwd)
+
+install_deps() {
+    # Setup SVF
+    echo "deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main" >> \
+        /etc/apt/sources.list
+    echo "deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-7 main" >> \
+        /etc/apt/sources.list
+    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|apt-key add -
+    apt -yqq update && apt -yqq upgrade
+    apt install -yqq llvm-7 clang-7
+    ln -s /usr/bin/clang-7 /usr/bin/clang
+    ln -s /usr/bin/llvm-link-7 /usr/bin/llvm-link
+    ln -s /usr/bin/llvm-ar-7 /usr/bin/llvm-ar
+}
+
+exports() {
+    export LLVM_SRC=/usr/local/installations/llvm-7.0.0.src
+    export LLVM_OBJ=/usr/lib/llvm-7/build
+    export LLVM_DIR=/usr/lib/llvm-7/build
+    export SVF_HOME=/usr/local/installations/SVF/
+    export PATH=$SVF_HOME/Release-build/bin:$PATH
+    export LLVM_COMPILER=clang
+}
+
+replace_cc() {
+    # replace '=' and ':=' with '?=' in rules Makefile, in templates Makefiles
+    sed -i -E "s/CC [:]?=/CC ?=/g" debian/rules
+    sed -i -E "s/CC[:]?=/CC?=/g" debian/rules
+    for i in Makefile*; do
+        sed -i -E "s/CC [:]?=/CC ?=/g" $i 2> /dev/null
+        sed -i -E "s/CC[:]?=/CC?=/g" $i 2> /dev/null
     done
-done
+}
+
+analysis() {
+    FILES=$@
+    extract_bc="extract-bc -b"
+
+    for i in $FILES; do
+        local name=$(basename $i)
+        local directory=$(dirname $i)
+        mkdir -p /callgraphs/$PKG/$directory
+        # extract LLVM bitcode
+        $extract_bc $i 2> error
+        STATUS=$?
+        if [ $STATUS != 0 ]; then
+            echo "$PKG: $i extract-bc error" >> /callgraphs/report && \
+                mv error /callgraphs/$PKG/$directory/$name.ext.err
+        elif [ -z "$i.bc" ]; then
+            echo "$PKG: $i no .bc file found" >> /callgraphs/report && \
+                if [ -z "error" ]; then
+                    mv error /callgraphs/$PKG/$directory/$name.ext.err
+                fi
+        else
+            # TODO Get warnings
+            wpa -fspta -dump-callgraph $i.bc 2> error
+            STATUS=$?
+            if [[ -f "callgraph_final.dot" ]]; then
+                echo "$PKG: $i done" >> /callgraphs/report && \
+                    mv callgraph_final.dot \
+                        /callgraphs/$PKG/$directory/$name.dot && \
+                    rm -f callgraph_initial.dot $i.bc
+            elif [[ -f "error" ]]; then
+                echo "$PKG: $i SVF failed" >> /callgraphs/report && \
+                    mv error /callgraphs/$PKG/$directory/$name.svf.err
+            fi
+        fi
+    done
+}
+
+run() {
+    # run SVF on package
+    CC=/usr/local/bin/wllvm dpkg-buildpackage -b 2>error
+    STATUS=$?
+    EXCECUTABLES=$(find -type f -executable -exec sh -c \
+        "file -i '{}' | grep -q 'x-executable; charset=binary'" \; -print)
+    ARCHIVES=$(find -type f -exec sh -c \
+        "file -i '{}' | grep -q 'x-archive; charset=binary'" \; -print)
+    SHAREDLIBS=$(find -type f -exec sh -c \
+        "file -i '{}' | grep -q 'x-sharedlib; charset=binary'" \; -print)
+    # Check if there are binaries
+    if [ -z "$EXCECUTABLES" ] && [ -z "$ARCHIVES" ] && \
+       [ -z "$SHAREDLIBS" ] && [ $STATUS == 0 ]; then
+        echo "$PKG: no binary files found" >> /callgraphs/report && \
+            exit 0
+    elif [[ -f "error" ]] && [ $STATUS != 0 ]; then
+        echo "$PKG: compilation failure" >> /callgraphs/report && \
+            mv error /callgraphs/$ERROR && \
+            rm -rf $PKG && \
+            exit 0
+    fi
+    # Create directory to save callgraphs and errors
+    mkdir -p /callgraphs/$PKG
+    if [ ! -z "$EXCECUTABLES" ]; then
+        analysis $EXCECUTABLES
+    fi
+    if [ ! -z "$ARCHIVES" ]; then
+        analysis $ARCHIVES
+    fi
+    if [ ! -z "$SHAREDLIBS" ]; then
+        analysis $SHAREDLIBS
+    fi
+}
+
+main () {
+    install_deps
+    exports
+    replace_cc
+    run
+}
+
+main
+exit 0
